import sys
import os
sys.path.insert(0, os.path.abspath('.'))

from odoo_cli import OdooClient

def main():
    client = OdooClient()
    client.connect()
    
    print("--- Creating new survey for Machu Picchu Exclusive Tours ---")
    
    # 1. Create the survey record
    survey_vals = {
        'title': "Encuesta de Satisfacción - Machu Picchu Exclusive Tours",
        'description': "<p>¡Gracias por elegirnos para vivir esta gran aventura! Tu opinión es muy valiosa para nosotros. Por favor tómate un minuto para responder las siguientes preguntas.</p>",
    }
    survey_id = client.create('survey.survey', survey_vals)
    print(f"[OK] Survey created with ID: {survey_id}")
    
    # Read the access token generated by Odoo
    survey_data = client.search_read('survey.survey', [('id', '=', survey_id)], fields=['access_token'])[0]
    access_token = survey_data['access_token']
    
    # 2. Add Questions
    questions = [
        {
            'title': "¿Cómo calificaría la amabilidad y conocimiento de su guía turístico?",
            'question_type': 'simple_choice',
            'survey_id': survey_id,
            'sequence': 10,
            'answers': ["Excelente", "Bueno", "Regular", "Malo"]
        },
        {
            'title': "¿Cómo calificaría la puntualidad y la logística general del tour?",
            'question_type': 'simple_choice',
            'survey_id': survey_id,
            'sequence': 20,
            'answers': ["Excelente", "Bueno", "Regular", "Malo"]
        },
        {
            'title': "¿El itinerario cubrió todas sus expectativas de viaje?",
            'question_type': 'simple_choice',
            'survey_id': survey_id,
            'sequence': 30,
            'answers': ["Superó mis expectativas", "Cumplió todas", "Cumplió la mayoría", "No cumplió"]
        },
        {
            'title': "¿Qué tan probable es que recomiende Machu Picchu Exclusive Tours a sus amigos o familiares?",
            'question_type': 'scale',
            'survey_id': survey_id,
            'sequence': 40,
            'scale_min': 1,
            'scale_max': 10,
            'scale_min_label': "Nada probable",
            'scale_max_label': "Muy probable"
        },
        {
            'title': "¿Tiene algún comentario adicional o sugerencia para mejorar nuestro servicio?",
            'question_type': 'text_box',
            'survey_id': survey_id,
            'sequence': 50
        }
    ]
    
    for q_data in questions:
        q_vals = {
            'title': q_data['title'],
            'question_type': q_data['question_type'],
            'survey_id': q_data['survey_id'],
            'sequence': q_data['sequence']
        }
        
        # Add scale fields if applicable
        if q_data['question_type'] == 'scale':
            q_vals.update({
                'scale_min': q_data['scale_min'],
                'scale_max': q_data['scale_max'],
                'scale_min_label': q_data['scale_min_label'],
                'scale_max_label': q_data['scale_max_label']
            })
            
        q_id = client.create('survey.question', q_vals)
        print(f"Created question: '{q_data['title']}' (ID: {q_id})")
        
        # Add answer options if the question type is simple_choice
        if q_data['question_type'] == 'simple_choice' and 'answers' in q_data:
            for idx, ans_text in enumerate(q_data['answers']):
                ans_vals = {
                    'question_id': q_id,
                    'value': ans_text,
                    'sequence': idx * 10
                }
                ans_id = client.create('survey.question.answer', ans_vals)
                print(f"  Added option: '{ans_text}' (ID: {ans_id})")
                
    base_url = client._base_url
    survey_url = f"{base_url}/survey/start/{access_token}"
    print(f"\n[SUCCESS] Survey setup complete!")
    print(f"Survey URL: {survey_url}")

if __name__ == '__main__':
    main()
